# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache: packages
warnings_are_errors: false

os:
  - osx
  
r_github_packages:
  - r-lib/covr
  
env:
  global:
  - MAKEFLAGS="-j 2"
  - PKG_LIBS="-llapack"

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master

